- platform: command_line
  command: /usr/bin/python /home/hass/.homeassistant/extraconfig/python_code/read_file.py nr1 Temperature
  name: flower_nr1_temp
  state_topic: "sensor/temperature"
  unit_of_measurement: "ºC"

- platform: command_line
  command: /usr/bin/python /home/hass/.homeassistant/extraconfig/python_code/read_file.py nr1 Light
  name: flower_nr1_light
  unit_of_measurement: "lx"

- platform: command_line
  command: /usr/bin/python /home/hass/.homeassistant/extraconfig/python_code/read_file.py nr1 Moisture
  name: flower_nr1_moist
  unit_of_measurement: "%"

- platform: command_line
  command: /usr/bin/python /home/hass/.homeassistant/extraconfig/python_code/read_file.py nr1 Fertility
  name: flower_nr1_fertility
  unit_of_measurement: "uS/cm"

- platform: command_line
  command: /usr/bin/python /home/hass/.homeassistant/extraconfig/python_code/read_file.py nr2 Temperature
  name: flower_nr2_temp
  state_topic: "sensor/temperature"
  unit_of_measurement: "ºC"

- platform: command_line
  command: /usr/bin/python /home/hass/.homeassistant/extraconfig/python_code/read_file.py nr2 Light
  name: flower_nr2_light
  unit_of_measurement: "lx"

- platform: command_line
  command: /usr/bin/python /home/hass/.homeassistant/extraconfig/python_code/read_file.py nr2 Moisture
  name: flower_nr2_moist
  unit_of_measurement: "%"

- platform: command_line
  command: /usr/bin/python /home/hass/.homeassistant/extraconfig/python_code/read_file.py nr2 Fertility
  name: flower_nr2_fertility
  unit_of_measurement: "uS/cm"

- platform: command_line
  command: /usr/bin/python /home/hass/.homeassistant/extraconfig/python_code/read_file.py nr3 Temperature
  name: flower_nr3_temp
  state_topic: "sensor/temperature"
  unit_of_measurement: "ºC"

- platform: command_line
  command: /usr/bin/python /home/hass/.homeassistant/extraconfig/python_code/read_file.py nr3 Light
  name: flower_nr3_light
  unit_of_measurement: "lx"

- platform: command_line
  command: /usr/bin/python /home/hass/.homeassistant/extraconfig/python_code/read_file.py nr3 Moisture
  name: flower_nr3_moist
  unit_of_measurement: "%"

- platform: command_line
  command: /usr/bin/python /home/hass/.homeassistant/extraconfig/python_code/read_file.py nr3 Fertility
  name: flower_nr3_fertility
  unit_of_measurement: "uS/cm"

#- platform: miflora
#  mac: C4:7C:8D:61:3C:D9
#  name: vaxt1
#  force_update: false
#  median: 3
#  monitored_conditions:
#   - moisture
#   - light
#   - temperature
#   - conductivity
